plugins {
    id 'java'
    id 'org.springframework.boot' version '2.1.17.RELEASE'
    id 'io.spring.dependency-management' version '1.0.10.RELEASE'
    id 'com.palantir.docker' version '0.25.0'
    id 'application'
}

apply from: 'http://gitlab.sh.com/ykas/devops/gradle-plugins/raw/springboot-1.0.1/common/build.gradle'


dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}


// dependencies
dependencies {
    /* common dependencies */
    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    // spring boot
    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }

    // sdk
    implementation 'org.apache.commons:commons-lang3'
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    implementation 'org.redisson:redisson:3.17.7'
    implementation 'com.github.luben:zstd-jni:1.5.5-10'

    implementation("com.alibaba:fastjson:2.0.49")

    implementation 'mysql:mysql-connector-java:8.0.33'

}

springBoot {
    mainClassName = 'com.dobest.sync.BootApplication'
}

